#!/bin/bash

echo "Starting X virtual frame buffer"
Xvfb :100 -screen 0 1600x1200x24 &

echo "Running Karma tests (time out in 30 sec)"
export DISPLAY=localhost:100
export CHROME_BIN=/usr/bin/chromium-browser
timeout 120 grunt karma:ci
TEST_STATUS=$?

echo "Tests done running, killing X virtual frame buffer"
pkill Xvfb

exit $TEST_STATUS
